import assert from 'node:assert/strict';import test from 'node:test';import{isQuietTime,dailySendAllowed,buildNotificationCandidates,buildContextualCandidates,buildOneSignalPayload,toDeliveryRow}from'./policy.js'
test('supports overnight quiet hours',()=>{assert.equal(isQuietTime('23:00','22:00','07:00'),true);assert.equal(isQuietTime('12:00','22:00','07:00'),false)})
test('caps ordinary sends but exempts explicit reminders',()=>{assert.equal(dailySendAllowed({sentToday:3,sentLastHour:0,explicit:false}),false);assert.equal(dailySendAllowed({sentToday:3,sentLastHour:1,explicit:true}),true)})
test('builds external alias OneSignal payload',()=>{const p=buildOneSignalPayload({userId:'u',title:'Hi',body:'Body',url:'/day',idempotencyKey:'00000000-0000-4000-8000-000000000000'});assert.equal(p.include_aliases.external_id[0],'u');assert.equal(p.target_channel,'push');assert.equal(p.idempotency_key,'00000000-0000-4000-8000-000000000000')})
test('materializes only due unsent task reminders',()=>{const now=new Date('2026-08-12T10:00:00Z');const rows=buildNotificationCandidates({preferences:{enabled:true},tasks:[{id:'due',title:'Pay rent',reminder_at:'2026-08-12T09:59:00Z',reminder_sent:false,completed:false},{id:'future',title:'Later',reminder_at:'2026-08-12T11:00:00Z',reminder_sent:false,completed:false},{id:'sent',title:'Already sent',reminder_at:'2026-08-12T09:00:00Z',reminder_sent:true,completed:false}],now});assert.deepEqual(rows.map(row=>row.sourceId),['due']);assert.equal(rows[0].body,'Pay rent')})
test('maps a candidate to an idempotent delivery row with its message content',()=>{const candidate={category:'task_reminder',sourceType:'task',sourceId:'task-1',logicalKey:'task:task-1:date',title:'Task reminder',body:'Pay rent',url:'/tasks/task-1'};assert.deepEqual(toDeliveryRow('user-1',candidate),{user_id:'user-1',logical_key:candidate.logicalKey,category:'task_reminder',source_type:'task',source_id:'task-1',bucket:'date',title:'Task reminder',body:'Pay rent',url:'/tasks/task-1'})})
test('builds morning, overdue, habit, and routine context in the user timezone',()=>{const rows=buildContextualCandidates({preferences:{enabled:true,timezone:'UTC',morning_time:'08:00',quiet_start:'22:00',quiet_end:'07:00',morning_planning:true,overdue_summary:true,habit_reminders:true,routine_reminders:true},tasks:[{id:'old',title:'Old',date:'2026-08-11',completed:false}],habits:[{id:'h1',name:'Walk'}],habitLog:[],routines:[{id:'r1',name:'Morning routine',time:'morning',steps:[{id:'s1'}]}],routineLog:{},dailyPriorities:{},now:new Date('2026-08-12T08:02:00Z')});assert.deepEqual(new Set(rows.map(row=>row.category)),new Set(['morning_planning','overdue_summary','habit_reminder','routine_reminder']))})
test('builds upcoming, focus, evening, and inactivity context without completed work',()=>{const rows=buildContextualCandidates({preferences:{enabled:true,timezone:'UTC',evening_time:'20:00',quiet_start:'23:00',quiet_end:'07:00',upcoming_tasks:true,focus_reminders:true,evening_review:true,inactivity_nudges:true,last_opened_at:'2026-08-10T10:00:00Z'},tasks:[{id:'soon',title:'Lesson',date:'2026-08-12',due_time:'20:15',completed:false},{id:'done',title:'Done',date:'2026-08-12',due_time:'20:10',completed:true}],focusSession:{taskId:'soon',status:'paused',lastTransitionAt:new Date('2026-08-12T19:30:00Z').getTime()},now:new Date('2026-08-12T20:02:00Z')});assert.deepEqual(new Set(rows.map(row=>row.category)),new Set(['upcoming_task','focus_reminder','evening_review','inactivity_nudge']));assert.equal(rows.some(row=>row.sourceId==='done'),false)})
test('quiet hours suppress contextual nudges but not explicit task reminders',()=>{const context=buildContextualCandidates({preferences:{enabled:true,timezone:'UTC',morning_time:'08:00',quiet_start:'07:00',quiet_end:'09:00',morning_planning:true},now:new Date('2026-08-12T08:01:00Z')});const explicit=buildNotificationCandidates({preferences:{enabled:true},tasks:[{id:'due',title:'Due',reminder_at:'2026-08-12T08:00:00Z',completed:false,reminder_sent:false}],now:new Date('2026-08-12T08:01:00Z')});assert.equal(context.length,0);assert.equal(explicit.length,1)})
