// Config: Tailwind with full DayFlow design system
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        '250': '250ms',
        '400': '400ms',
        '600': '600ms',
      },
      colors: {
        parchment: '#FAFAF8',
        forest: {
          50:  '#EEF4ED', 100: '#D0E4CC', 200: '#A7C9A0',
          400: '#5A9E6F', 500: '#3B6B4B', 700: '#2A4E36', 900: '#1A3222',
        },
        terracotta: { 50: '#FBF0EB', 500: '#C4622D', 700: '#9A4520' },
        ink: { DEFAULT: '#1A1A1A', muted: '#737373', faint: '#A8A29E' },
      },
      fontFamily: {
        serif: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        sans:  ['"Outfit"', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'card':  '0 1px 3px 0 rgb(0 0 0 / 0.04), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
        'card-hover': '0 4px 16px 0 rgb(0 0 0 / 0.08), 0 2px 4px -1px rgb(0 0 0 / 0.04)',
        'modal': '0 20px 60px -10px rgb(0 0 0 / 0.18)',
        'float': '0 8px 32px -4px rgb(59 107 75 / 0.35)',
      },
      keyframes: {
        fadeIn:       { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeUp:       { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeDown:     { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:      { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        slideUp:      { from: { transform: 'translateY(100%)' }, to: { transform: 'translateY(0)' } },
        slideRight:   { from: { opacity: '0', transform: 'translateX(-12px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        shimmer:      { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        bounceCheck:  { '0%': { transform: 'scale(0)' }, '60%': { transform: 'scale(1.2)' }, '100%': { transform: 'scale(1)' } },
        toastIn:      { from: { opacity: '0', transform: 'translateY(8px) scale(0.96)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        toastOut:     { from: { opacity: '1', transform: 'scale(1)' }, to: { opacity: '0', transform: 'scale(0.94)' } },
        float:        { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        pulseRing:    { '0%': { transform: 'scale(1)', opacity: '1' }, '100%': { transform: 'scale(1.5)', opacity: '0' } },
        springIn:     { '0%': { transform: 'scale(0.7)', opacity: '0' }, '60%': { transform: 'scale(1.05)' }, '80%': { transform: 'scale(0.97)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        ripple:       { '0%': { transform: 'scale(0)', opacity: '0.4' }, '100%': { transform: 'scale(2.5)', opacity: '0' } },
        xpFloat:      { '0%': { opacity: '1', transform: 'translateY(0) scale(1)' }, '60%': { opacity: '1', transform: 'translateY(-20px) scale(1.1)' }, '100%': { opacity: '0', transform: 'translateY(-36px) scale(0.9)' } },
        confettiFall: { '0%': { transform: 'translateY(-10px) rotate(0deg)', opacity: '1' }, '100%': { transform: 'translateY(60px) rotate(360deg)', opacity: '0' } },
        progressFill: { from: { width: '0%' }, to: { width: 'var(--target-width)' } },
        streakPop:    { '0%': { transform: 'scale(1)' }, '40%': { transform: 'scale(1.3)' }, '70%': { transform: 'scale(0.92)' }, '100%': { transform: 'scale(1)' } },
      },
      animation: {
        'fade-in':      'fadeIn 0.4s ease forwards',
        'fade-up':      'fadeUp 0.5s ease forwards',
        'fade-up-d1':   'fadeUp 0.5s 0.08s ease forwards',
        'fade-up-d2':   'fadeUp 0.5s 0.16s ease forwards',
        'fade-up-d3':   'fadeUp 0.5s 0.26s ease forwards',
        'fade-down':    'fadeDown 0.35s ease forwards',
        'scale-in':     'scaleIn 0.25s ease forwards',
        'slide-up':     'slideUp 0.4s cubic-bezier(0.32,0.72,0,1) forwards',
        'slide-right':  'slideRight 0.3s ease forwards',
        'shimmer':      'shimmer 1.6s linear infinite',
        'bounce-check': 'bounceCheck 0.3s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'toast-in':     'toastIn 0.3s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'toast-out':    'toastOut 0.2s ease forwards',
        'float':        'float 3s ease-in-out infinite',
        'pulse-ring':   'pulseRing 1.5s ease-out infinite',
        'spring-in':    'springIn 0.45s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'ripple':       'ripple 0.5s ease-out forwards',
        'xp-float':     'xpFloat 0.9s ease-out forwards',
        'confetti-fall':'confettiFall 0.8s ease-out forwards',
        'streak-pop':   'streakPop 0.4s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'slide-right-d1': 'slideRight 0.3s 0.05s ease forwards',
        'slide-right-d2': 'slideRight 0.3s 0.10s ease forwards',
        'slide-right-d3': 'slideRight 0.3s 0.15s ease forwards',
      },
    },
  },
  plugins: [],
}
