import { useEffect, useId, useState } from 'react'
import { parseCapture } from '../../services/captureParser'

const TYPES = ['task', 'reminder', 'note', 'idea', 'inbox']
export default function QuickCapture({ tasks, ideas, notes, inbox }) {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(''); const [type, setType] = useState('task'); const [done, setDone] = useState('')
  const titleId = useId()
  useEffect(() => { const handler = event => { if (event.type === 'dayflow:quickcapture' || (event.type === 'keydown' && (event.key === '+' || (event.key === 'q' && (event.metaKey || event.ctrlKey))))) { event.preventDefault?.(); setOpen(true) } else if (event.key === 'Escape') setOpen(false) }; window.addEventListener('keydown', handler); window.addEventListener('dayflow:quickcapture', handler); return () => { window.removeEventListener('keydown', handler); window.removeEventListener('dayflow:quickcapture', handler) } }, [])
  const submit = event => { event.preventDefault(); const parsed = parseCapture(input, type); if (parsed.type === 'task' || parsed.type === 'reminder') tasks.addTask(parsed.fields); else if (parsed.type === 'note') notes.addNote({ title: parsed.fields.title.slice(0, 40), content: parsed.text }); else if (parsed.type === 'idea') ideas.addIdea({ title: parsed.fields.title, category: 'Other' }); else inbox.add({ text: parsed.text, inferredType: parsed.type, fields: parsed.fields }); setDone(`${parsed.type} captured`); setInput(''); setTimeout(() => { setDone(''); setOpen(false) }, 700) }
  return <><button onClick={() => setOpen(true)} className="fixed bottom-20 right-4 md:bottom-6 md:right-6 z-[var(--z-nav)] w-14 h-14 rounded-full text-white text-2xl shadow-xl" style={{ backgroundColor: 'var(--accent)' }} aria-label="Quick capture">+</button>{open && <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4" style={{ backgroundColor: 'var(--overlay)' }} onClick={() => setOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby={titleId} className="w-full sm:max-w-md rounded-3xl p-5 animate-slide-up motion-reduce:animate-none" style={{ backgroundColor: 'var(--surface)' }} onClick={event => event.stopPropagation()}><h2 id={titleId} className="text-xs font-semibold uppercase tracking-widest">Quick Capture</h2><div className="flex flex-wrap gap-1 my-3">{TYPES.map(item => <button key={item} type="button" aria-pressed={type === item} onClick={() => setType(item)} className="rounded-full border px-3 py-1 text-xs capitalize" style={{ borderColor: type === item ? 'var(--accent)' : 'var(--border)' }}>{item}</button>)}</div><form onSubmit={submit}><label className="sr-only" htmlFor={`${titleId}-input`}>Capture text</label><input id={`${titleId}-input`} autoFocus value={input} onChange={event => setInput(event.target.value)} className="w-full rounded-2xl border px-4 py-3" style={{ backgroundColor: 'var(--bg)', borderColor: 'var(--border)', color: 'var(--text)' }} placeholder="What’s on your mind?"/><div className="flex gap-2 mt-4"><button type="button" onClick={() => setOpen(false)} className="flex-1 rounded-xl border py-2">Cancel</button><button disabled={!input.trim()} className="flex-1 rounded-xl py-2 text-white disabled:opacity-40" style={{ backgroundColor: 'var(--accent)' }}>Capture</button></div></form><p aria-live="polite" className="text-sm mt-2">{done}</p></section></div>}</>
}
